In [1]:
#Question 1:
#Fibonacci: F(n) = F(n-1) + F(n-2) ; F(1) = F(2) = 1
def F(num):
    if (num > 2):
        return F(num - 1) + F(num - 2)
    else:
        return 1
num = i = int(input("Enter a number: "))
nums = []
while(num > 0):
    nums.append(F(i - num + 1)) # nums = [1,1,2,3,5,...] not [...,5,3,2,1,1]
    num -= 1
print (nums)

Enter a number: 5
[1, 1, 2, 3, 5]


In [2]:
#Question 2:
#[n×n] Khayyam-Pascal Matrix:
import numpy as np
def KPM(n):
    Mat = np.zeros([n,n])
    for i in range(0,n):
        for j in range(0,n):
            if (j == 0) or (i == j):
                Mat[i,j] = 1
            elif (i > j):
                Mat[i,j] = Mat[i-1,j] + Mat[i-1,j-1]
    return Mat
n = int(input("Enter a number: "))
print (KPM(n))

Enter a number: 5
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 2. 1. 0. 0.]
 [1. 3. 3. 1. 0.]
 [1. 4. 6. 4. 1.]]


In [3]:
#Question 3:
#Replace one word with another:
def Rep(fname,w1,w2):
    f = open(fname + ".txt", 'rt')
    fnew = open("New " + fname + ".txt", 'wt')
    for w in f:
        fnew.write(w.replace(w1, w2))
    f.close()
    fnew.close()
#Enter file name like 'data' not 'data.txt'; (without '.txt')
#After every word enter ' , '; (space comma space)
[fname,w1,w2] = [(x) for x in input("Enter file name , first word , second word: ").split(" , ")]
Rep(fname,w1,w2)

Enter file name , first word , second word: data , Name, , ########sd


In [4]:
#Question 4:
#Dictionaries:
def dictor(fname):
    f = open(fname + ".txt", 'rt')
    lines = f.read().split('\n')
    line1 = lines[0].split(', ')
    lines = lines[1:]
    n = 0
    for i in lines:
        n += 1
    Dict={'first name': 'a' , 'last name': 'a' ,'age': 12 , 'height': 120 , 'weight':15 , 'nationality': 'i'}
    List = []
    for i in range(0,n):
        linei = lines[i].split(' * ')
        Dict['first name'] = linei[0].capitalize()
        Dict['last name'] = linei[1].capitalize()
        Dict['age'] = int(linei[2])
        Dict['height'] = int(linei[3])
        Dict['weight'] = int(linei[4])
        Dict['nationality'] = linei[5]
        d = Dict.copy()
        List.append(d)
    return List
fname = 'data'
print(dictor(fname))

[{'first name': 'Alex', 'last name': 'James', 'age': 25, 'height': 190, 'weight': 84, 'nationality': 'British'}, {'first name': 'Sara', 'last name': 'Anderson', 'age': 20, 'height': 160, 'weight': 98, 'nationality': 'American'}, {'first name': 'Roberto', 'last name': 'Carlos', 'age': 48, 'height': 183, 'weight': 78, 'nationality': 'Spanish'}, {'first name': 'Mohammad', 'last name': 'Amiri', 'age': 35, 'height': 190, 'weight': 77, 'nationality': 'Iranian'}]


In [13]:
#Question 5:
#Excel:
import numpy as np
import pandas as pd
df = pd.read_csv('Transcripts.csv')
m20 = df['Mark_20']
m4 = []
for i in m20:
    if (20 >= i) and (i >= 16):
        m4.append(4)
    elif (16 > i) and (i >= 14):
        m4.append(3)
    elif (14 > i) and (i >= 12):
        m4.append(2)
    elif (12 > i) and (i >= 10):
        m4.append(1)
    elif (10 > i) and (i >= 0):
        m4.append(0)
df['Mark_4'] = m4
df.to_csv('Transcripts2.csv',index=False)
GPA=sum((df['Credit'])*(df['Mark_4']))
GPA=GPA/sum(df['Credit'])
print(df,'\nGPA = %f'%(GPA))

                                      Course  Credit  Mark_20  Mark_4
0                                  Physics 1       3     20.0       4
1                                 Calculus 1       3     15.0       3
2                           English Language       3     20.0       4
3                           Persian Language       3     14.0       3
4                      Numerical Computation       2     14.5       3
5                     Differential Equations       3     18.0       4
6                                  Physics 2       3     19.5       4
7                                 Calculus 2       3     16.2       4
8                                      Sport       1     15.0       3
9   Introduction to Computer and Programming       4     12.0       2
10                          Electromagnetics       3     15.0       3
11    Engineering Probability and Statistics       3     14.0       3
12                   Engineering Mathematics       3     12.5       2 
GPA = 3.216216
